// Code generated by "stringer -linecomment -type Locale -output locales_string.go"; DO NOT EDIT.

package hsenum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocaleEnglish-0]
	_ = x[LocaleGerman-1]
	_ = x[LocaleFrench-2]
	_ = x[LocaleKorean-3]
	_ = x[LocaleChineseTraditional-4]
	_ = x[LocaleSpanish-5]
	_ = x[LocaleItalien-6]
	_ = x[LocalePolish-7]
}

const _Locale_name = "EnglishGermanFrenchKoreanChinese (Traditional)SpanishItalienPolish"

var _Locale_index = [...]uint8{0, 7, 13, 19, 25, 46, 53, 60, 66}

func (i Locale) String() string {
	if i >= Locale(len(_Locale_index)-1) {
		return "Locale(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Locale_name[_Locale_index[i]:_Locale_index[i+1]]
}
